### ISSUE TITLE
node_modules in source control

### ISSUE THREAD

**Issue by Grandrath** [jamesshore/lets_code_javascript#9]
I recently updated npm to version 3 and noticed that it now puts additional meta data into the `package.json` files beneath `node_modules/**/`. This meta data now includes absolute paths to the project directory, which makes it impossible to check those files into Git without causing merge conflicts.

I started using [`npm shrinkwrap`](https://docs.npmjs.com/cli/shrinkwrap) in my own projects. This creates an additional file that locks down all package versions to the currently installed ones. It doesn't solve the issue of being independent of third party services (AFAIK you'd need to set up a proxy for that) but at least it prevents different package versions caused by different checkout times.

**Comment by jamesshore** [comment]
That's interesting, and frustrating. I wonder if there's any way to get npm to rebuild that absolute path information.

If not, that's the death knell for checking in modules... something I'm not happy about. :-( A proxy doesn't solve the problem I really want to solve, which is having everything needed to build together in one repository. `npm shrinkwrap` also adds another error-prone step to the build process--forget to run it, and everything seems to work fine, until eventually an incompatible package is released.

**Comment by jamesshore** [comment]
@Grandrath I just updated weewikipaint to Node 5.0.0 and reinstalled all my modules to take advantage of npm's new "maximally flat" approach. I didn't see the issue you're referring to. I'm using npm v3.3.6.

To be specific, I saw that absolute paths are added to the `package.json` files, but I wasn't able to create any merge conflicts. Once installed, I wasn't able to get those paths to change, even with `npm rebuild` or `npm install`.

`npm shrinkwrap` has issues, so be careful with it. https://github.com/npm/npm/issues/5403

**Comment by Grandrath** [comment]
@jamesshore Just to clarify: I didn't run into issues with the absolute paths within `node_modules`. But I guess that npm uses them for *something* and I have no idea what might break when these paths are invalid e.g. in a clone on a differen machine.

> `npm shrinkwrap` also adds another error-prone step to the build process

You're right. But remembering to add `--ignore-scripts` to every install, commiting,  rebuilding and adjusting `.gitignore` correctly is not very straightforward either. ;-)

Thank you for pointing out the issue with `npm shrinkwrap`. I wasn't aware of that. :-(

----

I just played around with [sinopia](https://github.com/rlidwka/sinopia) a bit and it might help to solve this problem better. On its own it involves some (i.e. too many) steps but maybe it's possible to automate it.

What it does is running a local npm registry server. It can be configured to store the `.tgz` files for the packages in an arbitrary directory (within the version controlled project directory). All requests for packages that exist in this storage are answered without hitting the network. I think it'd much nicer to simply store the `.tgz` files instead of the huge tree beneath `node_modules`.

So how could a naïve workflow look like?

* Create a sinopia config within the project directory that sets the storage directory (e.g. `./npm-cache`)
* Create an npm config within the project directory that sets the registry to the sinopia server (e.g. `http://localhost:4873`)
* `npm install` as needed without doing anything special (besides starting the server that is)
* In a fresh clone on a different machine: Start the sinopia server and run `npm install`

Problems with this approach:

* Sinopia itself has to come from somewhere.
* Starting the server is something I'd like to see automated.

What do you think? Is this totally ridiculous or something that might be worth investigating further?

**Comment by jamesshore** [comment]
@Grandrath I think your paranoia regarding the absolute paths is justified. I've successfully cloned a npm v3 repo on another machine and to another path on the same machine, and I haven't run into any issues. But it's still a good question. I've opened https://github.com/npm/npm/issues/10393 to ask.

Regarding `--ignore-scripts`... that's fair. :-) But if you forget to do it, nothing bad happens. It fails safe, in contrast to `npm shrinkwrap`, which fails unsafe.

Checking in sinopia modules is an interesting idea, and worth exploring further. It's a pretty big layer of additional complexity, but like you said, it could be automated and the complexity hidden away. I think you could also automate server startup in a shell script pretty easily, perhaps with a small Node.js bootstrap program.

**Comment by jamesshore** [comment]
@Grandrath The npm folks report that there's no issue with moving node_modules to another location. See https://github.com/npm/npm/issues/10393#issuecomment-164063381. I'm going to go ahead and close this issue, but feel free to re-open if you want to.
